"""this is my third migration

Revision ID: 533f75b109ad
Revises: eb163e388f56
Create Date: 2019-09-22 20:12:43.071096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533f75b109ad'
down_revision = 'eb163e388f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
