"""this is my third migration

Revision ID: 84042849e617
Revises: 533f75b109ad
Create Date: 2019-09-23 00:02:46.484456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84042849e617'
down_revision = '533f75b109ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
